### ISSUE TITLE
Some entities not working

### ISSUE THREAD

**Issue by mattogodoy** [estevez-dev/ha_client_pub#1]
Hi!

I am giving the app a try and I can see there are some entities that are not working.

As far as I can see these are:
- History graph (https://www.home-assistant.io/components/history_graph/)
- Covers (https://www.home-assistant.io/components/cover/)
- Media player (https://www.home-assistant.io/components/media_player/)
- Binary sensor [badge] (https://www.home-assistant.io/components/binary_sensor/)
- Device tracker [badge] (https://www.home-assistant.io/components/device_tracker/)

This is how it looks in the app: https://i.imgur.com/3yNXNoG.jpg
This is how it looks in the browser: http://i.imgur.com/QDrB49o.png

I guess there are more, but these are the ones I use.
Thanks!

**Comment by estevez-dev** [comment]
Thanks for your report.
Indeed history graph, covers and media players is not supported yet.
But what is wrong with binary sensors and device trackers badges? I don't see them on both screenshots.

**Comment by mattogodoy** [comment]
Well, two of the tabs did not show and looking a the logs in the app I got `[Error] : Error parsing view: group.default_view`. Same error for the second view.

The only thing that is different between these views and the ones that work correctly are the binary sensors, so I guess that could be the problem. I could be wrong though.

**Comment by estevez-dev** [comment]
I see. I'll add more meaningful error messages to log to see what is wrong with that views.
Thanks.

**Comment by mattogodoy** [comment]
Ok! I'll let you know what the logs show when you do.

**Comment by estevez-dev** [comment]
Version 0.1.2-alpha published for testers. Will be available in Google Play soon. Your missing view should appear now. Check please after update. Thanks.

**Comment by mattogodoy** [comment]
You are correct!
The views are showing now.

This is the log output, just in case you need it:

```
[Debug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.resumed
[Debug] :  Socket connecting...
[Debug] :  [Received] => Message type: auth_required
[Debug] :  [Sending] ==> auth request
[Debug] :  [Received] => Message type: auth_ok
[Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
[Debug] :  [Sending] ==> {"id": 2, "type": "get_config"}
[Debug] :  [Received] => Message type: result
[Debug] :  [Received] => Message type: result
[Debug] :  [Sending] ==> {"id": 3, "type": "get_states"}
[Debug] :  [Received] => Message type: result
[Debug] :  Parsing 129 Home Assistant entities
[Debug] :  Gethering views
[Warning] :  Unknown entity inside view: alert.blinds_living
[Warning] :  Unknown entity inside view: sensor.mattoio
[Warning] :  Unknown entity inside view: sensor.mattoio_2
[Debug] :  [Sending] ==> {"id": 4, "type": "get_services"}
[Debug] :  [Received] => Message type: result
[Debug] :  Parsing 21 Home Assistant service domains
[Error] :  Exception: Couldn't download or retreive file.
[Debug] :  [Received] => Message type: event
[Debug] :  Parsing new state for sun.sun
[Debug] :  [Received] => Message type: event
[Debug] :  Parsing new state for sensor.tv_watching_this_week
[Debug] :  [Received] => Message type: event
[Debug] :  Parsing new state for binary_sensor.tv_status
[Debug] :  [Received] => Message type: event
[Debug] :  Parsing new state for binary_sensor.tv_status
```

**Comment by estevez-dev** [comment]
Nice! Thanks for replay. The reason was in non existing entities in views.
```
[Warning] :  Unknown entity inside view: alert.blinds_living
[Warning] :  Unknown entity inside view: sensor.mattoio
[Warning] :  Unknown entity inside view: sensor.mattoio_2
```

**Comment by estevez-dev** [comment]
As all other non supporting entities is planned to develop, I'll close this issue. Fill free to create new one if any. And please, try to report one problem in one issue for easy issue tracking. Thanks.
