### ISSUE TITLE
can't connect, time out code1

### ISSUE THREAD

**Issue by balvant813** [estevez-dev/ha_client_pub#18]
ebug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.resumed
[Debug] :  Settings change event: reconnect=true
[Debug] :  Socket connecting...
[Global error] :  WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242))
[Debug] :  Socket connecting...
[Global error] :  WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242))
[Debug] :  Settings change event: reconnect=true
[Debug] :  Socket connecting...
[Global error] :  WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242))
[Debug] :  Socket connecting...
[Global error] :  WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242))
[Debug] :  Settings change event: reconnect=true
[Debug] :  Socket connecting...
[Global error] :  WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242))
[Warning] :  Previous fetch is not complited
[Debug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.paused
[Debug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.resumed
[Debug] :  Socket connecting...
[Global error] :  WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242))

**Comment by estevez-dev** [comment]
The same as #5. Closing this as duplicate.
