### ISSUE TITLE
Missing default view

### ISSUE THREAD

**Issue by fernandex00** [estevez-dev/ha_client_pub#2]
I have a default View that it's not showing in the app, heres the screenshot
![377a318ae48ca527803f0bbb5c862636a6af8c51](https://user-images.githubusercontent.com/34770145/45950324-4c0e3300-bfcd-11e8-8400-63edca30edc2.jpeg)

**Comment by estevez-dev** [comment]
Thanks for the report. Will add additional parsing errors handler in next build to see what is wrong with that groups. Also it would be nice to see your configuration of group.default_view and one of the other groups causing parsing errors. Thanks!

**Comment by estevez-dev** [comment]
Version 0.1.2-alpha published for testers. Will be available in Google Play soon. There is skipping non existing groups and entities implemented as well as additional error handling. Check it after update. Thanks.

**Comment by fernandex00** [comment]
Got the update, working Well...

**Comment by estevez-dev** [comment]
Nice! Now I'm happy =) Thanks!
