### ISSUE TITLE
Open Source, Source Code?

### ISSUE THREAD

**Issue by thehaxxa** [estevez-dev/ha_client_pub#22]
Is the source code available?

Just curious on your plans with the project / licensing. I think the community would benefit from Open Development, but I understand if this is not your intent.

**Comment by estevez-dev** [comment]
I'm planning to make it open source. Not now, but after some more or less stable release.

**Comment by thehaxxa** [comment]
Good to hear, I am building a location tracking implementation for my own HA app, so if you're open to pull requests in the future I would be interested.

**Comment by efratomer** [comment]
As we talked few weeks ago, I would love to see this project moving forward as open source. Would totally give a hand.

**Comment by mattogodoy** [comment]
Count me in for the development!

**Comment by estevez-dev** [comment]
It is now open source: https://github.com/estevez-dev/ha_client/
