### ISSUE TITLE
Current temperature shows null when climate is set to auto operation mode.

### ISSUE THREAD

**Issue by w1ll1am23** [estevez-dev/ha_client_pub#25]
When climate is set to auto the current temp shows null but should should the upper and lower temps.

Screenshot from HA client app
![screenshot_ha_client_20181016-115912](https://user-images.githubusercontent.com/6432770/47030196-38bd3600-d13b-11e8-9da2-1fa2f0aaeeaa.png)

Screenshot from HA web
![screenshot_chrome_20181016-120204](https://user-images.githubusercontent.com/6432770/47030258-5d191280-d13b-11e8-9db9-1f16d6f6653c.png)

Screenshot form app when cool is selected
![screenshot_ha_client_20181016-135755](https://user-images.githubusercontent.com/6432770/47036967-affac600-d14b-11e8-8f34-634b0cdbe716.png)

**Comment by estevez-dev** [comment]
Please, show me a screenshot from app when operation mode is not auto. Thanks.

**Comment by w1ll1am23** [comment]
@estevez-dev added screenshot

**Comment by estevez-dev** [comment]
Ok, made a fix. Please recheck after next update. It will be available shortly.
Thanks.

**Comment by w1ll1am23** [comment]
@estevez-dev That worked, thanks.
