### ISSUE TITLE
Assumed state not honored for switches

### ISSUE THREAD

**Issue by w1ll1am23** [estevez-dev/ha_client_pub#30]
I have several switches that should be assumed state (two buttons on/off not a toggle switch) these are helpful for when something can be turned "on" multiple times. For example my TV volume is controlled by an assumed state switch and I can turn it "on" multiple times to increase the volume. With the app it's displayed as a toggle so I can only increase the volume and decrease the volume +/- 1. 

Picture of assumed state switches in HA web.
![assumed_state_switches](https://user-images.githubusercontent.com/6432770/47258375-573b6e00-d468-11e8-9c31-811d2c6c720b.png)

**Comment by estevez-dev** [comment]
Fixed in 0.3.3
Please test and confirm after update.

**Comment by w1ll1am23** [comment]
Works perfect, thanks!
