### ISSUE TITLE
Version 0.3.4

### ISSUE THREAD

**Issue by sajikur** [estevez-dev/ha_client_pub#34]
Lovelace UI crashes app. To re enter I must go in airplane mode and put normal mode again

**Comment by estevez-dev** [comment]
Is the app just closed, or you see a red screen with some errors on it?

**Comment by sajikur** [comment]
:)

In data 4 novembre 2018 10:27:50 Yegor Vialov <notifications@github.com> ha 
scritto:

**Comment by estevez-dev** [comment]
Does it means "No"?

**Comment by sajikur** [comment]
I sent it to you, please control your mail

In data 4 novembre 2018 10:55:11 Yegor Vialov <notifications@github.com> ha 
scritto:

**Comment by sajikur** [comment]
In data 4 novembre 2018 10:55:11 Yegor Vialov <notifications@github.com> ha 
scritto:

**Comment by estevez-dev** [comment]
I'm sorry, but there is no any screenshots. Looks like attaching images from emails not working on github. Please send the screenshot to vyalov.egor@gmail.com directly, or attaching to github issue through browser. Thanks a lot.

**Comment by sajikur** [comment]
Now?

Il domenica 4 novembre 2018, Yegor Vialov <notifications@github.com> ha
scritto:

**Comment by sajikur** [comment]
Perfect, good work!

In data 4 novembre 2018 11:28:14 Yegor Vialov <notifications@github.com> ha 
scritto:
