### ISSUE TITLE
App stays on Group view, even thought "use lovelace" is set. 

### ISSUE THREAD

**Issue by cholek3** [estevez-dev/ha_client_pub#36]
As the topic says. It does not matter if I set "use lovelace" in settings or not, main UI stays on "old" group view.
This is a log from app:

> 1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_pressure_3
1104 15:53:31 [Debug] :  ----Badge: sensor.disk_use_percent_home
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_humidity_1
1104 15:53:31 [Debug] :  ----Badge: sensor.memory_free
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_pressure_4
1104 15:53:31 [Debug] :  ----Badge: sensor.network_in_eth0
1104 15:53:31 [Debug] :  ----Creating card: light.light0
1104 15:53:31 [Debug] :  ----Creating card: automation.automation0
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_humidity_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_pressure_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_humidity_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_visibility
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_humidity_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_visibility_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_humidity_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_visibility_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_temperature
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_visibility_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_temperature
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_visibility_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_temperature_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_visibility_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_temperature_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_temperature_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_temperature_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_temperature_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_temperature
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_temperature_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_temperature_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_temperature_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_temperature_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_temperature_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_apparent_temperature
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_apparent_temperature
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_apparent_temperature_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_apparent_temperature_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_apparent_temperature_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_apparent_temperature_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daytime_high_apparent_temperature_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_apparent_temperature
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_apparent_temperature_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_apparent_temperature_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_apparent_temperature_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_apparent_temperature_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_overnight_low_apparent_temperature_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_speed
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_speed_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_speed_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_speed_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_speed_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_speed_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_bearing
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_bearing_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_bearing_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_bearing_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_bearing_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_wind_bearing_5
1104 15:53:31 [Debug] :  ----Badge: binary_sensor.fire_tv_box
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_probability
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_probability_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_probability_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_probability_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_probability_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_probability_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_accumulation
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_accumulation_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_accumulation_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_accumulation_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_accumulation_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_accumulation_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_intensity
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_intensity_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_intensity_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_intensity_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_intensity_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_precip_intensity_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daily_max_precip_intensity
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daily_max_precip_intensity_1
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_summary
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daily_max_precip_intensity_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daily_max_precip_intensity_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_daily_max_precip_intensity_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_icon_2
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_icon_3
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_icon_4
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_icon_5
1104 15:53:31 [Debug] :  ----Badge: sensor.dark_sky_icon_1
1104 15:53:31 [Debug] :  ----Badge: binary_sensor.hisensetv_lan
1104 15:53:31 [Debug] :  ----Creating card: media_player.media_player0
1104 15:53:31 [Debug] :  Fetch complete successful
1104 15:53:32 [Debug] :  [Received] => event.state_changed: sun.sun
1104 15:53:35 [Error] :  Exception: Couldn't download or retreive file.
1104 15:53:35 [Error] :  Exception: Couldn't download or retreive file.
1104 15:53:35 [Error] :  Exception: Couldn't download or retreive file.<

`

**Comment by cholek3** [comment]
Log after update to 0.3.5

>
1104 17:47:42 [Debug] :  AppLifecycleState.inactive
1104 17:47:42 [Debug] :  AppLifecycleState.resumed
1104 17:48:05 [Debug] :  Settings change event: reconnect=true
1104 17:48:05 [Debug] :  Use lovelace is true
1104 17:48:05 [Debug] :  Socket connecting...
1104 17:48:06 [Debug] :  [Sending] ==> auth request
1104 17:48:06 [Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
1104 17:48:06 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
1104 17:48:06 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
1104 17:48:06 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
1104 17:48:06 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
1104 17:48:06 [Debug] :  [Sending] ==> {"id": 6, "type": "auth/current_user"}
1104 17:48:06 [Debug] :  [Received] => id:1, success
1104 17:48:06 [Debug] :  [Received] => id:2, success
1104 17:48:06 [Debug] :  Parsing 181 Home Assistant entities
1104 17:48:06 [Debug] :  [Received] => id:4, success
1104 17:48:06 [Debug] :  [Received] => id:5, success
1104 17:48:06 [Debug] :  [Received] => id:6, success
1104 17:48:06 [Debug] :  [Received] => id:3, error
1104 17:48:06 [Error] :  There was an error getting Lovelace config: {id: 3, type: result, success: false, error: {code: file_not_found, message: Could not find ui-lovelace.yaml in your config dir.}}
1104 17:48:06 [Debug] :  Creating group-based UI
1104 17:48:06 [Debug] :  Fetch complete successful
1104 17:48:11 [Error] :  Exception: Couldn't download or retreive file.
1104 17:48:11 [Error] :  Exception: Couldn't download or retreive file.
1104 17:48:11 [Error] :  Exception: Couldn't download or retreive file.
1104 17:48:15 [Debug] :  [Received] => event.state_changed: sensor.current_time<

**Comment by estevez-dev** [comment]
Please update to 0.3.6 and provide logs once again. Thanks.

**Comment by estevez-dev** [comment]
You simply don't have a ui-lovelace.yaml. Your Lovelace UI is not configured

**Comment by cholek3** [comment]
Sorry, it was a typo. Second log is from 0.3.6. And I just found out my HA crashed. Will not load lovelace interface. It was working fine 2h ago.

**Comment by estevez-dev** [comment]
It is strange =(

**Comment by estevez-dev** [comment]
I also have a crash of HA recently. And also lost a samba share. I assume it depends on last updates of Home Assistant. Samba now requires username and password set up to work.

**Comment by estevez-dev** [comment]
I don't think it can be related to an app. HA Client perform exact the same things the regular Home Assistant web-based UI do.
