### ISSUE TITLE
Assumed state not honored for template cover

### ISSUE THREAD

**Issue by Kvasenok** [estevez-dev/ha_client_pub#39]
There was a similar issue with switches. In short, there is a setting for template covers "position_template" which sets the position of the cover to 50% (half open/half closed), it allows for both up and down buttons to be active at the same time. Since it is a template there is no actual cover and it is possible to use it for other use cases.
Similar closed issue: #30

**Comment by estevez-dev** [comment]
Could you please make your cover half opened and take a screenshot of it's attributes in the app?

**Comment by estevez-dev** [comment]
As you can see from state history in the app it is always "open". So I don't see a reason why it is not working =( Will check one more time.

**Comment by estevez-dev** [comment]
Ha, I found the reason!
It has 11 in supported_features. It means it is not supporting setting cover position. But in the same time it has current_position set. This is a mess in code of template cover. But still I can fix that it app.

**Comment by Kvasenok** [comment]
Awesome, works fine with the last update)
