### ISSUE TITLE
View cut off

### ISSUE THREAD

**Issue by w1ll1am23** [estevez-dev/ha_client_pub#4]
Minor issue, the last view in my view tabs is cut off. 

https://photos.app.goo.gl/bLg2pxtGTp5qc3dm6

**Comment by estevez-dev** [comment]
Whoa, it is a lot of views ))
Is it not possible to scroll tab icons horizontally?

**Comment by w1ll1am23** [comment]
I think it might be, but I think I have just the correct amount or something for it to think it doesn't need to scroll? I can try adding another when I get home.

**Comment by estevez-dev** [comment]
It would be nice. Please try to add another one. Thanks

**Comment by w1ll1am23** [comment]
Adding another view made it worse. Now the line doesn't show up under the correct view. I added 4 more after that and they just get closer and closer together and cut the last one off more and more.

**Comment by estevez-dev** [comment]
A see. Ok. Will fix that. Thanks.

**Comment by estevez-dev** [comment]
Fixed in 0.3.0
