### ISSUE TITLE
Change size fonts

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client_pub#43]
But my suggestion is change to smaller size font because some devices show to short… Look on screen 
Problem is on my Huawei P10
![30baaed3ebb1fb09ea8b74bae498b1ff207e658c](https://user-images.githubusercontent.com/16692223/48066372-abb34d00-e1cd-11e8-94e7-8f33b5cbf059.jpeg)

**Comment by estevez-dev** [comment]
Ha Client is now an open source project so issue tracking is moved to it's main repository.
You can subscribe to an issue in main repo to track it's status: estevez-dev/ha_client#171
