### ISSUE TITLE
Sortting tabs is other in app and other on web

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client_pub#46]
Problem with sortting tabs is still in latest version app and HA 0.81.6
In app order tabs is other than on web browser.
Looks
Web browser
![web](https://user-images.githubusercontent.com/16692223/48212217-6fbdea80-e37b-11e8-9365-44d7723e908c.jpg)

In app
![screenshot_20181108-172448](https://user-images.githubusercontent.com/16692223/48212330-aac01e00-e37b-11e8-95e6-49653bc2daa0.jpg)

**Comment by estevez-dev** [comment]
Is is a lovelace ui?
