### ISSUE TITLE
Hide header with scroll

### ISSUE THREAD

**Issue by Kvasenok** [estevez-dev/ha_client_pub#47]
I don't know if it can be considered a bug or if it is more of a feature request, but still, I just think it would be closer to default Android app behavior and to the web UI if the header title would "hide" when scrolling down, leaving only tabs visible. 
But one should consider app's behavior and animation when switching from scrolled down tab with hidden header to a tab which has just a few entities and therefore is not supposed to be scrolled down and have the header hidden.

**Comment by estevez-dev** [comment]
Ha Client is now an open source project so issue tracking is moved to it's main repository.
Your issue is there as well: estevez-dev/ha_client#178

**Comment by estevez-dev** [comment]
Subscribe to new issue to get updates.
