### ISSUE TITLE
Connection to the server failed [OS Error: WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by eyalgindi** [estevez-dev/ha_client_pub#5]
HA 0.1.2
Pocophone f1,  Android 8.1 MIUI 9.6

Debug] :  Socket connecting...
[Global error] :  WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error:  WRONG_VERSION_NUMBER(tls_record.cc:242))

**Comment by estevez-dev** [comment]
This is a strange one. Will check. Thanks for report.

**Comment by estevez-dev** [comment]
I need more information on this. Do you connect to a local IP or external one? Do you use HTTPS?
Thanks.

**Comment by eyalgindi** [comment]
No HTTPS
Local and remote with port fwd
Resolved when switched ROM to vanilla, might be something with Xiaomi miui

**Comment by estevez-dev** [comment]
Ah, looks like it is. Thanks. Closing for now.
