### ISSUE TITLE
front page not loading

### ISSUE THREAD

**Issue by jyjx85** [estevez-dev/ha_client_pub#6]
![screenshot_20180925-101950](https://user-images.githubusercontent.com/37039300/45989156-05900580-c0ad-11e8-9b99-7f2ab019e0d3.jpg)
![screenshot_20180925-101940](https://user-images.githubusercontent.com/37039300/45989163-0c1e7d00-c0ad-11e8-8ec6-b2c2b14c45ba.jpg)

**Comment by estevez-dev** [comment]
You don't have group_default_view in your groups.yaml, right? If so, then this is in progress now. Will be ready in next version. Thanks for report.

**Comment by wpmjones** [comment]
I have the same issue and I do not have a default_view in my groups.yaml. I look forward to the next version.

**Comment by estevez-dev** [comment]
Yes, automatically generated default_view is in development now. Be patient and thanks for taking part in testing.

**Comment by estevez-dev** [comment]
Resolved in 0.2.0
