### ISSUE TITLE
Missing icons and tabs dashboard is sorted other than on web

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client_pub#8]
Hi
I use 0.1.2 alpha and HA 0.78.3
Some icons is missing like: mediaplayer, calendar google, and scenes...

Also tabs dashboard is not sorted the same as in WEB browser...
![screenshot_20180925-094934](https://user-images.githubusercontent.com/16692223/46001578-ea70c600-c0ab-11e8-8394-63290d9e17cd.jpg)

![screenshot_20180925-095010](https://user-images.githubusercontent.com/16692223/46001585-efce1080-c0ab-11e8-910d-411dc6b2ebb2.jpg)

**Comment by estevez-dev** [comment]
Thanks for the report. Will take those issues in work.

**Comment by pepeEL** [comment]
Icon for media player and scenes now works ok in version 0.1.3
But still no icon for Google Calendar and Alarm Panel...and also sorted dashboard is still no fix.

**Comment by estevez-dev** [comment]
Yes. Still in progress

**Comment by estevez-dev** [comment]
@pepeEL Do you use "order" in your groups configuration?

**Comment by pepeEL** [comment]
No i don't use order

**Comment by pepeEL** [comment]
Sorting tabs is still in problem. It is in other order in app and other than in web browser... It should be fixed...

**Comment by estevez-dev** [comment]
Yes, I know. I just can't figure out how it is sorted on web, because this issue is not reproduced for me. Looks like I need to dig HA sources.

**Comment by estevez-dev** [comment]
Ha Client is now an open source project so issue tracking is moved to it's main repository.
Please follow this issue to get updates: estevez-dev/ha_client#85
