### ISSUE TITLE
App only shows default_view no other groups 0.1.2-alpha

### ISSUE THREAD

**Issue by bl0rp** [estevez-dev/ha_client_pub#9]
When opening the app only the default_view is shown. No other groups are selectable or displayed.

Link to my group file:
https://github.com/bl0rp/Home-AssistantConfig/blob/master/groups/views.yaml

no errors in the log, only updates for entities from other groups/views.

**Comment by estevez-dev** [comment]
So, any way, force app to close, launch it gain, wait for ui to show views, copy log here.
And some questions:

1. Do you see those groups in web interface?
2. Do you have some customization for that groups? Icons, order, something else?

**Comment by bl0rp** [comment]
Did close the app already and nothing changed. 
I'll post the log but there are no errors in it.

the web interface is working (if not I would not post here ;))  some groups use mdi icons some use names (like "ELW")...

it was working yesterday with the prev. version

logfile:

> Debug] : Parsing new state for automation.sonoff4_load_logfile
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff3_uptime
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff3_spannung
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff3_stromstaerke
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff3_momentane_leistung
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for automation.sonoff3_load_logfile
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff2_uptime
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff2_verbrauch_heute
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff2_momentane_leistung
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff2_spannung
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff2_stromstaerke
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff3_stromstaerke
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff3_momentane_leistung
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for automation.sonoff2_load_logfile
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for automation.sonoff3_load_logfile
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for automation.sonoff2_load_lcd
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff3_stromstaerke
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.sonoff3_momentane_leistung
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for automation.sonoff3_load_logfile
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.ha_uptime_in_seconds
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.ha_uptime_human
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.dns_queries_today
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.queries_cached
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.mosquitto_broker_messages_received
[Debug] : [Received] => Message type: event
[Debug] : Parsing new state for sensor.mosquitto_broker_messages_sent

**Comment by estevez-dev** [comment]
I asked to force close the app and launch it again to see connecting and entities parsing logs.

**Comment by bl0rp** [comment]
I did force close the app but there is no scroll in the log and that's everything i see after 2 seconds runtime

**Comment by estevez-dev** [comment]
Hm... Ok. Thanks for report and quick replay. Will try to figure out what's wrong.

**Comment by estevez-dev** [comment]
Hi. Could you please try on a version 0.1.3? It should work or at least will show reasonable errors in log. Thanks.

**Comment by estevez-dev** [comment]
@bl0rp ?

**Comment by bl0rp** [comment]
solved in latest update. sorry.
